// Code generated by sqlc. DO NOT EDIT.

import type { Sql } from "postgres";

export interface GetAuthorArgs {
    id: number;
}

export interface GetAuthorRow {
    id: number;
    name: string;
    bio: string | null;
}

export async function getAuthor(sql: Sql, args: GetAuthorArgs): Promise<GetAuthorRow | null> {
    const rows = await sql<GetAuthorRow[]> `SELECT id, name, bio FROM authors
WHERE id = ${args.id} LIMIT 1`;
    return rows[0] ?? null;
}

export interface ListAuthorsRow {
    id: number;
    name: string;
    bio: string | null;
}

export async function listAuthors(sql: Sql): Promise<ListAuthorsRow[]> {
    return await sql<ListAuthorsRow[]> `SELECT id, name, bio FROM authors
ORDER BY name`;
}

export interface CreateAuthorArgs {
    name: string;
    bio: string | null;
}

export interface CreateAuthorRow {
    id: number;
    name: string;
    bio: string | null;
}

export async function createAuthor(sql: Sql, args: CreateAuthorArgs): Promise<CreateAuthorRow | null> {
    const rows = await sql<CreateAuthorRow[]> `INSERT INTO authors (
  name, bio
) VALUES (
  ${args.name}, ${args.bio}
)
RETURNING id, name, bio`;
    return rows[0] ?? null;
}

export interface DeleteAuthorArgs {
    id: number;
}

export async function deleteAuthor(sql: Sql, args: DeleteAuthorArgs): Promise<void> {
    await sql `DELETE FROM authors
WHERE id = ${args.id}`;
}

